---
- hosts: raspberry
  become: true

  pre_tasks:
    - name: Load configuration (with defaults from example file).
      ansible.builtin.include_vars: "config.yml"

    - name: Ensure apt cache is up to date.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when:
        - ansible_facts.os_family == "Debian"

  handlers:
    - name: Include handlers.
      ansible.builtin.import_tasks: tasks/handlers.yml

  tasks:
    - name: Setup Docker.
      ansible.builtin.import_tasks: tasks/docker.yml

    - name: Set up Pi Hole.
      ansible.builtin.import_tasks: tasks/pi-hole.yml
      when: pihole_enable

    - name: Set up unifi.
      ansible.builtin.import_tasks: tasks/unifi.yml
      when: unifi_enable

    - name: Set up omada.
      ansible.builtin.import_tasks: tasks/omada.yml
      when: omada_enable

    - name: Set up adguard.
      ansible.builtin.import_tasks: tasks/adguard.yml
      when: adguard_enable

    - name: Set up crontab job
      ansible.builtin.import_tasks: tasks/crontab.yml
      when: crontab_enable
