---
- name: Configure Raspberry Pi
  hosts: raspberry
  become: true

  pre_tasks:
    - name: Load configuration (with defaults from example file).
      ansible.builtin.include_vars: "config.yml"

    - name: Ensure apt cache is up to date.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when:
        - ansible_facts.os_family == "Debian"

  handlers:
    - name: Include handlers.
      ansible.builtin.import_tasks: tasks/handlers.yml

  tasks:
    - name: Configure network.
      ansible.builtin.import_tasks: tasks/network.yml

    - name: Install Argon ONE script.
      ansible.builtin.import_tasks: tasks/argonone.yml

    - name: Setup Docker.
      ansible.builtin.import_tasks: tasks/docker.yml

    - name: Configure unattended upgrades
      ansible.builtin.import_tasks: tasks/unattended_upgrades.yml

    - name: Set up AdGuard.
      ansible.builtin.import_tasks: tasks/adguard.yml
      when: adguard_enable

    - name: Set up OpenSpeedTest.
      ansible.builtin.import_tasks: tasks/openspeedtest.yml
      when: open_speed_test_enable

    - name: Set up Watchtower.
      ansible.builtin.import_tasks: tasks/watchtower.yml
      when: watchtower_enable
