- name: Copy update script folder to Pi.
  ansible.builtin.copy:
    src: containers/update_container_images.sh
    dest: "{{ config_dir }}"
    mode: '0740'
  become: false

- name: Ensure a job that runs at 3 am and updates docker containers exists"
  ansible.builtin.cron:
    name: "update containers"
    minute: "0"
    hour: "3"
    job: "{{ config_dir }}/update_container_images.sh"
    user: "{{ ansible_user }}"