---
- name: Restart pi-hole
  community.docker.docker_compose_v2:
    project_src: "{{ config_dir }}/pi-hole/"
    build: never
    state: restarted
  become: false

- name: Restart unifi
  community.docker.docker_compose_v2:
    project_src: "{{ config_dir }}/unifi/"
    build: never
    state: restarted
  become: false

- name: Restart omada
  community.docker.docker_compose_v2:
    project_src: "{{ config_dir }}/omada/"
    build: never
    state: restarted
  become: false

- name: Restart adguard
  community.docker.docker_compose_v2:
    project_src: "{{ config_dir }}/adguard/"
    build: never
    state: restarted
  become: false