---
- name: Restart pi-hole
  community.docker.docker_compose_v2:
    project_src: "{{ config_dir }}/pi-hole/"
    build: never
    state: restarted
  become: false

- name: Restart adguard
  community.docker.docker_compose_v2:
    project_src: "{{ config_dir }}/adguard/"
    build: never
    state: restarted
  become: false

- name: Restart openspeedtest
  community.docker.docker_compose_v2:
    project_src: "{{ config_dir }}/openspeedtest/"
    build: never
    state: restarted
  become: false

- name: Restart watchtower
  community.docker.docker_compose_v2:
    project_src: "{{ config_dir }}/watchtower/"
    build: never
    state: restarted
  become: false
