---
- name: Restart openspeedtest
  community.docker.docker_compose_v2:
    project_src: "{{ config_dir }}/openspeedtest/"
    build: never
    state: restarted
  become: false

- name: Restart watchtower
  community.docker.docker_compose_v2:
    project_src: "{{ config_dir }}/watchtower/"
    build: never
    state: restarted
  become: false
