---
- name: Create Pi-hole folder on Pi.
  ansible.builtin.file:
    path: "{{ config_dir }}/pi-hole"
    state: directory
    mode: '0755'
  become: false

- name: Create dnscrypt-proxy folder on Pi.
  ansible.builtin.file:
    path: "{{ config_dir }}/pi-hole/etc-dnscrypt-proxy"
    state: directory
    mode: '0777'
  become: false

- name: Copy dnscrypt-proxy config to Pi.
  ansible.builtin.copy:
    src: containers/pi-hole/etc-dnscrypt-proxy/dnscrypt-proxy.toml
    dest: "{{ config_dir }}/pi-hole/etc-dnscrypt-proxy"
    mode: '0755'
  become: false

- name: Copy Pi-hole docker-compose template to Pi.
  ansible.builtin.copy:
    src: containers/pi-hole/docker-compose.yml
    dest: "{{ config_dir }}/pi-hole/docker-compose.yml"
    mode: '0640'
  become: false
  notify: Restart pi-hole

# TODO: The first time this playbook is run, the `pi` user may not be added
# to the `docker` group, so this task may fail.
- name: Ensure Pi-hole is running.
  community.docker.docker_compose_v2:
    project_src: "{{ config_dir }}/pi-hole/"
    build: never
  become: false